name: Sync dbus.dev to dbus.fun
on:
    push:
    schedule:
        - cron: '0 0/7 * * *'
jobs:
    move:
        name: OneDrive Sync dbus.dev to dbus.fun
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Sync
          run: |
              # Start Mission
              bash sync-dbus-fun.sh
